In [21]:
import numpy as np
import random
import matplotlib as mpl
import matplotlib.pyplot as plt
import time

tamanhos = [5000, 10000, 15000, 20000, 25000, 30000]
tempo = []

def complexidade_temporal(metodo): 
    def decorator_temporal(args, **kwargs): # arr
        tempoInicial = time.perf_counter()
        chamadaDeMetodo = metodo(args, **kwargs)
        tempoFinal = time.perf_counter()

        return chamadaDeMetodo, tempoFinal - tempoInicial
    return decorator_temporal

##### **MÉTODOS DE ORDENAÇÃO**=> algoritmos que visam organizar dados seguindo um critério específico na menor quantidade de tempo possível
**PARAMÊTROS:**
*   **Número de trocar e inversões** => quantas vezes os elementos trocam de posição?
*   **Número de comparações** => quantas vezes se verifica se um elemento é menor ou maior que outro?
*   **Recursão** => usa ou não?
*   **Estabilidade** => caso um elemento possua o mesmo valor que outro, o algoritmo devolve eles na ordem que eles são encontrados na sequência inicial?
*   **Espaço extra** => além da entrada, quanto espaço esse algoritmo requer?









##### **BUBBLE SORT** => *bolhas maiores sobem mais rápido*
*   Ordena elementos em ordem **crescente**
*   Compara elementos adjacentes (lado a lado)
*   Se o **primeiro** elemento for **maior que** o **segundo**, o primeiro **assume a posição** do segundo e vice-versa
*   O **maior elemento** é sempre usado para **comparar**

In [32]:
for tamanho in tamanhos: 
    lista = np.random.randint(0, 1000, size=tamanho)
    for i in range(len(lista)):
        for j in range(0, len(lista)-i-1):
            if lista[j] > lista[j+1]:
                aux = lista[j]
                lista[j] = lista[j + 1]
                lista[j + 1] = aux

KeyboardInterrupt: 

**COMPLEXIDADE TEMPORAL - Bubble Sort** 
* **Melhor caso:** *O(n)*
* **Caso médio:** *O(n^2)*
* **Pior caso:** *O(n^2)*

##### **INSERTION SORT** => *jogo de cartas*
*  Compara os **2 primeiros** elementos
*  Se o **próximo** for **maior**, ele **troca** de **posição** com o **anterior**
*  Se **não** houverem mais **elementos anteriores** para **comparar**, ele **prossegue**
*  Caso haja uma **troca**, o **menor elemento** é **comparado** com os **anteriores**
*  Mesmo que hajam trocas, as **comparações** com os **elementos anteriores** só **termina** quando **não houverem mais elementos antes**

In [33]:
for tamanho in tamanhos: 
      for i in range(len(lista)):
            lista = np.random.randint(0, 100, size=tamanho)
            aux = lista[i]
            j = i - 1
            while j >= 0 and lista[j] > aux:
                  lista[j + 1] = lista[j]
                  j = j - 1
            lista[j + 1] = aux


KeyboardInterrupt: 

**COMPLEXIDADE TEMPORAL - Insertion Sort**
* **Melhor caso:** *O(n)*
* **Caso médio:** *O(n^2)*
* **Pior caso:** *O(n^2)*

##### **SELECTION SORT** => *troca nos extremos*
*   O primeiro item é chamado de ***mínimo***
*   O item ***mínimo*** é comparado com o segundo item => se o segundo item for menor, ele deverá ser o novo ***mínimo***
*   A cada iteração, o ***mínimo*** é posto na posição final da lista de números não ordenados
*   Repita esse processo até o item final, atribuindo um novo ***mínimo*** sempre que necessário


In [31]:
for i in range(len(lista) - 1):
      lista = np.random.randint(0, 100, size=tamanho)
      minimo = i
      for j in range (i + 1, len(lista)):
          if lista[j] < lista[minimo]:
            minimo = j
      aux = lista[i]
      lista[i] = lista[minimo]
      lista[minimo] = aux

**COMPLEXIDADE TEMPORAL - Selection Sort**
* **Melhor caso:** *O(n^2)*
* **Caso médio:** *O(n^2)*
* **Pior caso:** *O(n^2)*

##### **QUICK SORT** => *dividir a* ***sequência de números*** *e conquistar a* ***solução***

*   Um elemento da lista é escolhido como **pivô**
*   Os elementos **menores** que o **pivô** ficam à **esquerda** e os elementos **maiores** que o **pivô** ficam à **direita**
*   É comum se referir à essa divisão feita pela escolha do pivô como **partições** -> essas partições se formam a partir de comparações que se dão de maneira recursiva
*   O algoritmo faz constantemente **comparações** entre o **elemento esquerdo com o elemento direito**

**OBSERVAÇÕES**

1.  O quick sort se baseia na técnica de **divisão e conquista** => ele é uma das formas de construir **algoritmos eficientes**
2.  A escolha do pivô pode afetar a **complexidade temporal** do algoritmo, até mesmo em listas pequenas.
3.  A maneira mais segura de escolher um pivô é selecionar o elemento do meio do array
4. O quick sort usa recursão

In [42]:
#CRÉDITOS AO PROFESSOR RONALDO QUE ME AJUDOU A IMPLEMENTAR ESSE MÉTODO <3
#Nao funciona mais :( 
particaoDireita = []
particaoEsquerda = []
particaoMeio = []

for tamanho in tamanhos:
   lista = np.random.randint(0, 100, size=tamanho)

   if len(lista) <= 1:
      print(lista)

   pivo = lista[int(len(lista)/2)]

def quick_sort(particaoDireita, particaoMeio, particaoEsquerda):
   for i in lista:
      if i < pivo:
         particaoEsquerda.append(i)
      if i > pivo:
         particaoDireita.append(i)
      if i == pivo:
         particaoMeio.append(i)

   return quick_sort(particaoEsquerda) + particaoMeio + quick_sort(particaoDireita)

quick_sort(particaoDireita, particaoEsquerda, particaoMeio)

TypeError: quick_sort() missing 2 required positional arguments: 'particaoMeio' and 'particaoEsquerda'

**COMPLEXIDADE TEMPORAL - Quick Sort**

* **Melhor caso:** O(n $\cdot$ log n)
* **Caso médio:** O(n $\cdot$ log n)
* **Pior caso:** O(n^2)

##### **SHELL SORT** => *insertion sort, só que melhor*

* Um número N que corresponde ao número de elementos na lista é sucessivamente dividido por 2 
* A cada loop, N é novamente dividido por 2 conforme a necessidade, se tornando N/2, N/4, N/8 e assim por diante.
* Importante ressaltar que, quando isso ocorre, a distância entre os elementos fica menor.
* Quando ⌊N/2⌋ = 0, a ordenação chega ao fim, pois não existe mais espaço entre os elementos

In [44]:
for tamanho in tamanhos:
    lista = np.random.randint(0, 100, size=tamanho)
    espaco = len(lista)//2
    
    while espaco > 0: 
        for i in range(espaco, len(lista)): 
            aux = lista[i] 
            j = i 
            while j >= espaco and lista[j - espaco] > aux: 
                lista[j] = lista[j - espaco] 
                j -= espaco 
            lista[j] = aux 
        espaco = espaco // 2
    print(lista)



[ 0  0  0 ... 99 99 99]
[ 0  0  0 ... 99 99 99]
[ 0  0  0 ... 99 99 99]
[ 0  0  0 ... 99 99 99]
[ 0  0  0 ... 99 99 99]
[ 0  0  0 ... 99 99 99]


**OBSERVAÇÕES**
* A sequência original do Shell Sort é dada por $\lfloor N/2^k \rfloor$ 
* Existem outras sequências que podem ser aplicadas no Shell Sort: 
    1. Sequência de Knuth = ***\(3^k - 1\)***
    2. Sequência de Sedgewick = ***\(4^i + 3 $\cdot$ 2^{i-1} + 1 , $para$ i $\geq$ 1 \)***
    3. Sequência de Hibbard = ***\(2^k - 1 , $para$ k $\geq$ 1\)***
    4. Sequência de Papernov e Stasevich = ***\(2^{k + 1} - 3 $para$ k $\cdot$ 1\)***
    5. Sequência de Pratt = ***\(2, 3, 5, 7, 11...\)** :. números primos em ordem crescente*  
* Dependendo do problema, outras sequências podem se mostrar mais eficientes 

**COMPLEXIDADE TEMPORAL**

##### **MERGE SORT** => *dividir, conquistar e* ***combinar***

* Outro método de ordenação que usa **divisão e conquista**
* A lista de elementos é dividida ao **meio** em **sublistas** e assim por diante **até cada elemento ficar isolado**
* Terminadas as divisões, os elementos são **comparados** de **dois em dois** e **ordenados** numa **sublista**
* Os **elementos das sublistas** formadas por esse processo vão sendo **comparados** e **ordenados** até **formar a lista final**, com todos os **elementos originais ordenados**

In [56]:
lista = np.random.randint(0, 100, size=tamanho)
if len(lista) <= 1:
      print(lista)

#operador // realiza uma divisao inteira
particaoMeio = len(lista)//2
#elementos antes de particaoMeio - 1
particaoEsquerda = lista[:particaoMeio]
#elementos depois de particaoMeio - 1
particaoDireita = lista[particaoMeio:]

def merge_sort():
      #combina particaoDireita e particaoEsquerda juntando-as na lista original
      while i < len(particaoEsquerda) and j < len(particaoDireita):
            #condição que compara e ordena os elementos menores
            if particaoEsquerda[i] <= particaoDireita[j]:
                  lista[k] = particaoEsquerda[i]
                  i += 1
            #condição que compara e ordena os elementos maiores
            else:
                  lista[k] = particaoDireita[j]
                  j += 1
            k += 1

      #verifica se há elementos restantes em particaoEsquerda
      while i < len(particaoEsquerda):
            lista[k] = particaoEsquerda[i]
            i += 1
            k += 1

      #verifica se há elementos restantes em particaoDireita
      while j < len(particaoDireita):
            lista[k] = particaoDireita[j]
            j += 1
            k += 1

      return lista 

for tamanho in tamanhos:
      merge_sort(particaoDireita)
      merge_sort(particaoEsquerda)
      i = j = k = 0

merge_sort()

TypeError: merge_sort() missing 2 required positional arguments: 'particaoEsquerda' and 'particaoMeio'

**COMPLEXIDADE TEMPORAL**

* O(n $\cdot$ log n)
* Mesma complexidade temporal independente do caso

##### **COUNTING SORT** => *não usa comparações*

* Contaremos o **número de ocorrências** de um certo elemento na lista desordenada numa outra lista com **número de elementos igual ao valor máximo** da lista original, mas todos os elementos serão **zero**, pois ainda não conhecemos as ocorrências
* Em seguida, percorremos a lista original novamente para **reordená-la baseada na lista de ocorrências**.
* Se **houver ocorrência**, o **valor do índice** onde ela ocorreu será **armazenado dentro da lista**.
* Tendo feito isso, **decrementaremos** em **1** o **número de ocorrências** naquele **índice**.

In [57]:
for tamanho in tamanhos:
    lista = np.random.randint(0, 1000, size=100)    
    #ocorrencias antes de examinar a lista -> como não temos certeza, é tudo zero 
    contagem_de_ocorrencias = [0] * (max(lista) + 1)
    
    #contagem_de_ocorrencias possui 21 elementos, sendo o último o elemento máximo dentro da lista, pois contamos a partir do 0 
    #o valor do elemento será guardado num índice correspondente ao seu valor da contagem_de_ocorrencias
    
    for i in lista: 
        contagem_de_ocorrencias[i] += 1
        
    #j será o contador que vai reordenar a lista
        
    j = 0 
    
    #se houver ocorrência, ou seja, contagem_de_ocorrencia > 0, o índice de onde ocorreu será armazenado na lista 
    #j é incrementado e seguimos para o próximo elemento dentro da lista original 
    #o índice da contagem_de_ocorrencias é decrementado uma vez que a ocorrência já foi registrada na lista original
    
    for i in range(len(contagem_de_ocorrencias)):
        while contagem_de_ocorrencias[i] > 0:
            lista[j] = i
            j += 1
            contagem_de_ocorrencias[i] -= 1
            
    print(lista)

[ 10  18  25  25  47  49  61  62  71 103 116 117 138 146 148 156 166 175
 193 199 203 209 210 214 223 234 245 250 270 275 288 297 308 321 322 326
 342 363 386 393 396 403 411 416 416 416 423 435 452 456 458 479 488 491
 511 512 517 524 545 563 564 591 594 595 595 598 600 613 638 639 646 672
 685 713 713 729 757 766 773 789 795 798 808 811 849 852 868 869 872 917
 943 944 946 947 953 954 965 972 985 986]
[  4  13  51  55  57  61  63  68  72  82  85  99 101 107 118 120 120 167
 174 178 178 180 186 217 231 233 242 252 274 286 298 305 307 315 316 317
 418 433 444 449 479 482 486 501 504 512 525 528 531 532 533 540 542 543
 549 578 580 583 605 619 626 640 647 648 651 667 675 700 704 720 722 739
 744 751 758 760 762 779 799 802 810 822 826 834 846 846 864 896 906 909
 921 922 932 954 965 967 967 969 977 997]
[ 11  18  27  34  73  84  86 101 108 108 111 158 160 161 184 188 215 230
 237 238 246 252 253 256 263 277 284 293 317 328 338 345 346 350 352 359
 380 385 395 402 431 432 444 455 456 459

**COMPLEXIDADE TEMPORAL**

* O(n + k)
* Mesma complexidade temporal independente do caso

### **BUCKET SORT**

In [55]:
@complexidade_temporal 
def bucket_sort(lista):
    bucket = len(lista)/2
    return bucket

lista = random.sample(range(100000), 100)

500.0

### **RADIX SORT**

### **HEAP SORT**

### **COCKTAIL SORT** 

### **COMB SORT**

### **BITONIC SORT**